wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713826856.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.9
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
k:
  desc: null
  value: 0.47526260205078735
lr1:
  desc: null
  value: 0.001
n_max:
  desc: null
  value: 0.04577459569806822
nep:
  desc: null
  value: 20
β:
  desc: null
  value: 0.5008550694595653
γ:
  desc: null
  value: 0.5440589883084517
δ:
  desc: null
  value: 0.4803803556137466
