wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713694535.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 23
      - 37
      4: 3.10.9
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
k:
  desc: null
  value: 0.5704875391601046
lr1:
  desc: null
  value: 0.01
n_max:
  desc: null
  value: 0.05481739199741508
nep:
  desc: null
  value: 25
β:
  desc: null
  value: 0.5159340689196299
γ:
  desc: null
  value: 0.5814495021868674
δ:
  desc: null
  value: 0.4376865363391364
