wandb_version: 1

attacks:
  value: noise
defense:
  value: cosine
iteration:
  value: 50
k:
  value: 0.1
lr:
  value: 0.001
m_r:
  value: 0.15
max_t:
  value: 2000
nep:
  value: 100
noise:
  value: 1
non_iid:
  value: 0.5
temp:
  value: 0.1
