# python main.py --set CIFAR10 --model "Conv8" --batch_size 32 --FL_global_epochs 500 --lr 0.4  --data_loc "./cifar10/data/" --data_backdoor "./cifar10/data/backdoor" --FL_type "FRL_matrix_attack" 
# python main.py --set CIFAR10 --model "Conv8" --batch_size 32 --FL_global_epochs 1000 --lr 0.4  --data_loc "./cifar10/data/" --data_backdoor "./cifar10/data/backdoor" --FL_type "other_attacks_Fang" 
# python main.py --set CIFAR10 --model "Conv8" --batch_size 32 --FL_global_epochs 1000 --lr 0.4  --data_loc "./cifar10/data/" --data_backdoor "./cifar10/data/backdoor" --FL_type "FRL_label_flip_fang" 
# python main.py --set CIFAR10 --model "Conv8" --batch_size 32 --FL_global_epochs 100 --lr 0.4  --data_loc "./cifar10/data/" --data_backdoor "./cifar10/data/backdoor" --FL_type "FRL_matrix_attack" 
# python main.py --set CIFAR10 --model "Conv8" --batch_size 32 --FL_global_epochs 1000 --lr 0.4  --data_loc "./cifar10/data/" --data_backdoor "./cifar10/data/backdoor" --FL_type "FRP_defense" 
# python main.py --set CIFAR10 --model "Conv8" --batch_size 32 --FL_global_epochs 1000 --lr 0.4  --data_loc "./cifar10/data/" --data_backdoor "./cifar10/data/backdoor" --FL_type "FRL_defense_Fang" 
# python main.py --set CIFAR10 --model "Conv8" --batch_size 32 --FL_global_epochs 200 --lr 0.4  --data_loc "./cifar10/data/" --data_backdoor "./cifar10/data/backdoor" --FL_type "FRL_fang" 
# python main.py --set CIFAR10 --model "Conv8" --batch_size 32 --FL_global_epochs 100 --lr 0.4  --data_loc "./cifar10/data/" --data_backdoor "./cifar10/data/backdoor" --FL_type "FRL_train_defense_val" 
# python main.py --set CIFAR10 --model "Conv8" --batch_size 32 --FL_global_epochs 100 --lr 0.4  --data_loc "./cifar10/data/" --data_backdoor "./cifar10/data/backdoor" --FL_type "other_attacks_val" 
# python main.py --set CIFAR10 --model "Conv8" --batch_size 32 --FL_global_epochs 500 --lr 0.4  --data_loc "./cifar10/data/" --data_backdoor "./cifar10/data/backdoor" --FL_type "my_attack_defense" 

# python main.py --set CIFAR10 --model "Conv8" --batch_size 32 --local_epochs 4 --FL_global_epochs 300 --lr 0.4  --data_loc "./cifar10/data/" --data_backdoor "./cifar10/data/backdoor" --FL_type "my_attack_defense" 
# python main.py --set CIFAR10 --model "Conv8" --batch_size 32 --local_epochs 4 --FL_global_epochs 2000 --lr 0.4  --data_loc "./cifar10/data/" --data_backdoor "./cifar10/data/backdoor" --FL_type "my_attack_defense" 
# python main.py --set CIFAR10 --model "Conv8" --batch_size 32 --local_epochs 6 --FL_global_epochs 2000 --lr 0.4  --data_loc "./cifar10/data/" --data_backdoor "./cifar10/data/backdoor" --FL_type "my_attack_defense" 

# python main.py --set CIFAR10 --model "VGG" --batch_size 8 --local_epochs 5 --FL_global_epochs 500 --lr 0.4  --data_loc "./cifar10/data/" --round_nclients 5 --rand_mal_clients 5 --FL_type "FRL_fang" 
# python main.py --set CIFAR100  --model "Conv8_100" --batch_size 8 --FL_global_epochs 500 --lr 0.5  --data_loc "./cifar100/data/" --round_nclients 5 --rand_mal_clients 5 --FL_type "FRL_fang"

# python main.py --set CIFAR10 --model "VGG" --batch_size 8 --local_epochs 5 --FL_global_epochs 2000 --lr 0.4  --data_loc "./cifar10/data/" --data_backdoor "./cifar10/data/backdoor" --FL_type "my_attack_defense" 
# python main.py --set CIFAR10 --model "Conv8" --batch_size 32 --local_epochs 25 --FL_global_epochs 2000 --lr 0.4  --data_loc "./cifar10/data/" --data_backdoor "./cifar10/data/backdoor" --FL_type "my_attack_defense" 
# python main.py --set CIFAR10 --model "Conv8" --batch_size 32 --local_epochs 30 --FL_global_epochs 2000 --lr 0.4  --data_loc "./cifar10/data/" --data_backdoor "./cifar10/data/backdoor" --FL_type "my_attack_defense" 
# python main.py --set CIFAR10 --model "Conv8" --batch_size 32 --local_epochs 35 --FL_global_epochs 2000 --lr 0.4  --data_loc "./cifar10/data/" --data_backdoor "./cifar10/data/backdoor" --FL_type "my_attack_defense" 
# python main.py --set CIFAR10 --model "Conv8" --batch_size 32 --FL_global_epochs 500 --lr 0.4  --data_loc "./cifar10/data/" --data_backdoor "./cifar10/data/backdoor" --FL_type "FRL_matrix_attack" 
python main.py --set CIFAR10 --model "Conv8" --batch_size 32 --FL_global_epochs 1000 --lr 0.4  --data_loc "./cifar10/data/" --data_backdoor "./cifar10/data/backdoor" --FL_type "Reverse_mid" 
python main.py --set Fashion --model "LeNet" --batch_size 32 --local_epochs 2 --FL_global_epochs 1000 --lr 0.4  --data_loc "./Fashion/data/"  --FL_type "Reverse_mid" 
