# python main.py --set Fashion --model "LeNet" --batch_size 32 --FL_global_epochs 300 --lr 0.4  --data_loc "./Fashion/data/" --data_backdoor "./Fashion/data/backdoor" --FL_type "other_attacks" 
# # python main.py --set Fashion --model "LeNet" --batch_size 32 --FL_global_epochs 300 --lr 0.4  --data_loc "./Fashion/data/" --data_backdoor "./Fashion/data/backdoor" --FL_type "other_attacks_Fang" 
# python main.py --set Fashion --model "LeNet" --batch_size 32 --FL_global_epochs 300 --lr 0.4  --data_loc "./Fashion/data/" --data_backdoor "./Fashion/data/backdoor" --FL_type "FRL_label_flip_fang" 
# python main.py --set Fashion --model "LeNet" --batch_size 32 --FL_global_epochs 300 --lr 0.4  --data_loc "./Fashion/data/" --data_backdoor "./Fashion/data/backdoor" --FL_type "FRL_label_flip" 
# # python main.py --set Fashion --model "LeNet" --batch_size 32 --FL_global_epochs 100 --lr 0.4  --data_loc "./Fashion/data/" --data_backdoor "./Fashion/data/backdoor" --FL_type "FRL_matrix_attack" 
# python main.py --set Fashion --model "LeNet" --batch_size 32 --FL_global_epochs 300 --lr 0.4  --data_loc "./Fashion/data/" --data_backdoor "./Fashion/data/backdoor" --FL_type "FRP_defense" 
# python main.py --set Fashion --model "LeNet" --batch_size 32 --FL_global_epochs 300 --lr 0.4  --data_loc "./Fashion/data/" --data_backdoor "./Fashion/data/backdoor" --FL_type "FRL_defense_Fang" 
# # python main.py --set Fashion --model "LeNet" --batch_size 32 --FL_global_epochs 300 --lr 0.4  --data_loc "./Fashion/data/" --data_backdoor "./Fashion/data/backdoor" --FL_type "FRL_fang" 
# # python main.py --set Fashion --model "LeNet" --batch_size 32 --FL_global_epochs 100 --lr 0.4  --data_loc "./Fashion/data/" --data_backdoor "./Fashion/data/backdoor" --FL_type "FRL_train_defense_val" 
# python main.py --set Fashion --model "LeNet" --batch_size 32 --FL_global_epochs 300 --lr 0.4  --data_loc "./Fashion/data/" --data_backdoor "./Fashion/data/backdoor" --FL_type "other_attacks_Fang" 
# python main.py --set Fashion --model "LeNet" --batch_size 32 --FL_global_epochs 100 --lr 0.4  --data_loc "./Fashion/data/" --data_backdoor "./Fashion/data/backdoor" --FL_type "other_attacks" 
# python main.py --set Fashion --model "LeNet" --batch_size 32 --FL_global_epochs 300 --lr 0.4  --data_loc "./Fashion/data/" --data_backdoor "./Fashion/data/backdoor" --FL_type "other_attacks" 
# python main.py --set Fashion --model "LeNet" --batch_size 32 --local_epochs 2 --FL_global_epochs 500 --lr 0.4  --data_loc "./MNIST/data/" --data_backdoor "./MNIST/data/backdoor" --FL_type "my_attack_defense" 
python main.py --set Fashion --model "LeNet" --batch_size 32 --local_epochs 2 --FL_global_epochs 500 --lr 0.4  --data_loc "./Fashion/data/"  --FL_type "my_attack_defense" 
# python main.py --set CIFAR10 --model "Conv8" --batch_size 32 --local_epochs 4 --FL_global_epochs 1000 --lr 0.4  --data_loc "./MNIST/data/" --data_backdoor "./MNIST/data/backdoor" --FL_type "my_attack_defense" 
# python main.py --set MNIST --model "Conv2" --batch_size 32 --local_epochs 4 --FL_global_epochs 1000 --lr 0.4  --data_loc "./MNIST/data/" --data_backdoor "./MNIST/data/backdoor" --FL_type "my_attack_defense" 

# python main.py --set Fashion --model "LeNet" --batch_size 32 --local_epochs 6 --FL_global_epochs 500 --lr 0.4  --data_loc "./MNIST/data/" --data_backdoor "./MNIST/data/backdoor" --FL_type "my_attack_defense" 
# python main.py --set Fashion --model "LeNet" --batch_size 32 --local_epochs 8 --FL_global_epochs 500 --lr 0.4  --data_loc "./MNIST/data/" --data_backdoor "./MNIST/data/backdoor" --FL_type "my_attack_defense" 
# python main.py --set Fashion --model "LeNet" --batch_size 32 --local_epochs 10 --FL_global_epochs 500 --lr 0.4  --data_loc "./MNIST/data/" --data_backdoor "./MNIST/data/backdoor" --FL_type "my_attack_defense" 
