# python main.py --set CIFAR10 --model "Conv8" --batch_size 16 --lr 0.1 --data_loc "./cifar10/data/" --data_backdoor "./cifar10/data/backdoor" --FL_type "FRL" 
# python main.py --set FEMNIST --model "LeNet" --batch_size 16 --lr 0.4  --data_loc "./femnist/data/" --data_backdoor "./femnist/data/backdoor" --FL_type "FRL" 
python main.py --set FEMNIST --model "LeNet" --batch_size 16 --data_loc "./femnist/data/" --data_backdoor "./femnist/data/backdoor" --FL_type "FedAVG" 
# python main.py --set FEMNIST --model "LeNet" --batch_size 16 --data_loc "./femnist/data/" --data_backdoor "./femnist/data/backdoor" --FL_type "Tr_Mean" 
# python main.py --set FEMNIST --model "LeNet" --batch_size 16 --data_loc "./femnist/data/" --data_backdoor "./femnist/data/backdoor" --FL_type "Mkrum" 
python main.py --set FEMNIST --model "LeNet" --batch_size 16 --lr 0.4  --data_loc "./femnist/data/" --data_backdoor "./femnist/data/backdoor" --FL_type "other_attacks" 
python main.py --set FEMNIST --model "LeNet" --batch_size 16 --lr 0.4 - -data_loc "./femnist/data/" --data_backdoor "./femnist/data/backdoor" --FL_type "FRL_label_flip" 
python main.py --set FEMNIST --model "LeNet" --batch_size 16 --lr 0.4  --data_loc "./femnist/data/" --data_backdoor "./femnist/data/backdoor" --FL_type "FRL_matrix_attack" 
python main.py --set FEMNIST --model "LeNet" --batch_size 16 --lr 0.4  --data_loc "./femnist/data/" --data_backdoor "./femnist/data/backdoor" --FL_type "FRL_cosine" 
python main.py --set FEMNIST --model "LeNet" --batch_size 16 --lr 0.4  --data_loc "./femnist/data/" --data_backdoor "./femnist/data/backdoor" --FL_type "FRL_fang" 
python main.py --set FEMNIST --model "LeNet" --batch_size 16 --lr 0.4  --data_loc "./femnist/data/" --data_backdoor "./femnist/data/backdoor" --FL_type "FRL_defense_cosine" 
python main.py --set FEMNIST --model "LeNet" --batch_size 16 --lr 0.4  --data_loc "./femnist/data/" --data_backdoor "./femnist/data/backdoor" --FL_type "FRL_defense_Fang" 
python main.py --set FEMNIST --model "LeNet" --batch_size 16 --lr 0.4  --data_loc "./femnist/data/" --data_backdoor "./femnist/data/backdoor" --FL_type "other_attacks_Fang" 