wandb_version: 1

k_s:
  value: 1
lr1:
  value: 0.1
lr2:
  value: 0.001
nep:
  value: 100
scale1:
  value: 100
scale2:
  value: 1000
v:
  value: 0.5
α:
  value: 0.5
β:
  value: 0.7
γ:
  value: 0.7
δ:
  value: 0.001
