wandb_version: 1

k_s:
  value: 5
lr1:
  value: 0.1
lr2:
  value: 0.01
nep:
  value: 50
scale1:
  value: 10
scale2:
  value: 1000
v:
  value: 0.3
α:
  value: 0.7
β:
  value: 0.5
γ:
  value: 0.9
δ:
  value: 0.001
