wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713910242.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.9
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
k:
  desc: null
  value: 0.41178617320116345
lr1:
  desc: null
  value: 0.001
n_max:
  desc: null
  value: 0.05027390556124689
nep:
  desc: null
  value: 25
β:
  desc: null
  value: 0.40030017471278745
γ:
  desc: null
  value: 0.5995042604862899
δ:
  desc: null
  value: 0.4226242380270339
