wandb_version: 1

k_s:
  value: 1
lr1:
  value: 1
lr2:
  value: 0.001
nep:
  value: 25
scale1:
  value: 10
scale2:
  value: 1000
v:
  value: 0.7
α:
  value: 0.3
β:
  value: 0.7
γ:
  value: 1
δ:
  value: 0.001
