wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713620878.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.9
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
k:
  desc: null
  value: 0.5912363107668155
lr1:
  desc: null
  value: 0.01
nep:
  desc: null
  value: 10
α:
  desc: null
  value: 0.5505167131332496
β:
  desc: null
  value: 0.5838232502394943
γ:
  desc: null
  value: 0.529323534978192
δ:
  desc: null
  value: 0.5586001806671103
