wandb_version: 1

k_s:
  value: 1
lr1:
  value: 0.1
lr2:
  value: 0.01
nep:
  value: 5
scale1:
  value: 100
scale2:
  value: 100
v:
  value: 0.7
α:
  value: 0.5
β:
  value: 0.5
γ:
  value: 2
δ:
  value: 0.001
