wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713753334.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.9
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
k:
  desc: null
  value: 0.5200074672384447
lr1:
  desc: null
  value: 0.001
n_max:
  desc: null
  value: 0.04635047648598103
nep:
  desc: null
  value: 25
β:
  desc: null
  value: 0.5991902137164797
γ:
  desc: null
  value: 0.5948559737375922
δ:
  desc: null
  value: 0.4507612750013454
