wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718528063.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.9
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
FL_type:
  desc: null
  value: FRL_cosine
attacks:
  desc: null
  value: grad_ascent
defense:
  desc: null
  value: cosine
iteration:
  desc: null
  value: 50
k:
  desc: null
  value: 0.1
lr:
  desc: null
  value: 0.001
m_r:
  desc: null
  value: 0.2
max_t:
  desc: null
  value: 2000
nep:
  desc: null
  value: 100
noise:
  desc: null
  value: 1
non_iid:
  desc: null
  value: iid
temp:
  desc: null
  value: 0.1
