wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712659483.0
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 23
      4: 3.10.9
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
k_s:
  desc: null
  value: 30
lr:
  desc: null
  value: 0.04468924927335493
n_s:
  desc: null
  value: 30
Î±:
  desc: null
  value: 0.2
