wandb_version: 1

k_s:
  value: 5
lr1:
  value: 0.01
lr2:
  value: 0.001
nep:
  value: 20
scale1:
  value: 10
scale2:
  value: 1000
v:
  value: 0.5
α:
  value: 0.5
β:
  value: 0.7
γ:
  value: 2
δ:
  value: 0.001
