wandb_version: 1

attacks:
  value: min_sum
iteration:
  value: 50
k:
  value: 0.1
lr:
  value: 0.001
m_r:
  value: 0.2
max_t:
  value: 2000
mode:
  value: LFR
nep:
  value: 100
noise:
  value: 1
non_iid:
  value: 0.3
temp:
  value: 0.1
