wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718497861.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 23
      - 24
      - 37
      4: 3.10.9
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
defense:
  desc: null
  value: FRL
k:
  desc: null
  value: 0.1
m_r:
  desc: null
  value: 0.2
non_iid:
  desc: null
  value: 1
