wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713621228.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.9
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
k:
  desc: null
  value: 0.4657014846794852
lr1:
  desc: null
  value: 0.01
n_max:
  desc: null
  value: 0.057226132584141096
nep:
  desc: null
  value: 20
β:
  desc: null
  value: 0.446334632189653
γ:
  desc: null
  value: 0.5722970957003287
δ:
  desc: null
  value: 0.4547512869780338
