wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713472662.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 23
      - 37
      4: 3.10.9
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
k_s:
  desc: null
  value: 5
lr1:
  desc: null
  value: 0.01
lr2:
  desc: null
  value: 0.001
nep:
  desc: null
  value: 100
scale1:
  desc: null
  value: 100
scale2:
  desc: null
  value: 100
v:
  desc: null
  value: 0.7
α:
  desc: null
  value: 0.5
β:
  desc: null
  value: 0.3
γ:
  desc: null
  value: 1.5
δ:
  desc: null
  value: 0.001
