wandb_version: 1

FL_type:
  value: FRL_cosine
attacks:
  value: min_sum
defense:
  value: cosine
iteration:
  value: 50
k:
  value: 0.1
lr:
  value: 0.001
m_r:
  value: 0.2
max_t:
  value: 2000
nep:
  value: 100
noise:
  value: 1
non_iid:
  value: iid
temp:
  value: 0.1
